### ISSUE TITLE
Lost line_notify library in fugle_realtime_restful_api  requirements.txt

### ISSUE THREAD

**Issue by JasperSui** [fortuna-intelligence/fugle-realtime-demo#2]
The README.md in fugle_realtime_restful_api directory mentioned line_noitfy,

but the requirements.txt did not include line-notify.

Please fix it, thanks!

```
line_notify==0.1.4
```

**Comment by JasperSui** [comment]
Sorry for misunderstanding, I thought it was an external library.

**Comment by JasperSui** [comment]
I'll close this issue and please ignore it, I appreciate your instant reply very much!

**Comment by thstarshine** [comment]
> Sorry for misunderstanding, I thought it was an external library.

That's ok. I have just made a wrong pull request either. :laughing:
